title: Arjun Das
description: Personal Website
baseurl: ""

username: Arjun Das
typing_text: Data Scientist

email: arjun.das6842@gmail.com
telegram_username: 
linkedin_username: arjundas12
github_username: arjundas1
facebook_username: 
viber_number: 

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://drive.google.com/file/d/10WTwm6y3_4gpjvDp9bFhYdWNUUq21gJ7/view?usp=share_link

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: arjundas1/arjundas1.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - arjundas1.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - arjundas1

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
